### ISSUE TITLE
Related project

### ISSUE THREAD

**Issue by camjac251** [ltriant/sidegate#1]
Hey

I came across your project when looking at new go projects and thought maybe to mention this.

Have you tried croc for sending files? It's also written in go and cross platform. It works over LAN as well.

https://github.com/schollz/croc/

**Comment by ltriant** [comment]
Hi,

Thanks for reaching out :) I hadn't come across croc, and it looks like an awesome project. I love the blog posts around it, explaining clearly why the project was started.

There are a couple of reasons it doesn't suit my own personal use-cases:

If I'm sending the file, it requires the receiver to be a little more tech-savvy and they need to run a command-line tool. While that's great for some people I know, it may be too complicated for others. And for some who have locked-down work laptops, they can't access the command prompt at all. I like the web interface to appeal to those users, because almost everyone has access to a browser.

It solves a problem I don't personally have, which is sending files over the internet, rather than just within a local network. And because it's solving this problem, it also requires a relay server in the middle (to get around port-forwarding), which is an extra bit of architectural complexity I didn't want to deal with.

Of course, if I ever want to use my project to interact over the internet with my own friends, then the port-forwarding issue is going to be a problem for me, in which case a project like croc would be great.

**Comment by camjac251** [comment]
Try it out sometime. I wish I found it sooner. I sort of setup a context menu shortcut workflow (on Windows) for sending and receiving so it avoids having to use the command line.
For receiving, you don't need to use cli. If you open the binary file, itll popup with a terminal window asking for the receive code (I mean still using command line but it doesnt require typing `croc receive`
Also too, there's a public relay that is set it be used by default when you start a transfer so setting up a new one isn't required. For local transfers, I think the send command sets one up automatically when you send

**Comment by ltriant** [comment]
Ah that's interesting! I haven't used Windows in so many years I have pretty much no idea what you can/can't do with it :)

I'll definitely check it out, because it _does_ look interesting.
